version: "2.1"
services:
  db:
    volumes:
      - ${PROJECT_ROOT}/db:/docker-entrypoint-initdb.d:ro
  # Browser
  browser:
    hostname: browser
    image: selenium/standalone-chrome
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
